[discord]
token = <discord_bot_token>
bot_owner_id = <user_id>
repeater_owner_role_id = <role_id>
role_channel_id = <channel_id>
feed_channel_id = <channel_id>
purge_days = 4

[api]
api_enabled = False
api_url = <api_url>
api_poll_interval = 900

[mqtt]
mqtt_enabled = False
mqtt_url = <url>
mqtt_port = <port>
mqtt_username = <username>
mqtt_password = <password>
mqtt_transport = websockets
mqtt_ws_path = /
mqtt_tls = True
mqtt_topics = meshcore/<IATA>/+/packets

[region_logs]
# Map region codes to log file names
# If a region is not mapped, it will use the region code as the log name
<IATA> = <log_name>

[meshmap]
url = <url>

[node_watcher]
enabled = true
interval_seconds = 60

[<category_id>]
hash_size = <hash_size>
nodes_file = <nodes_file>
removed_nodes_file = <removed_nodes_file>
reserved_nodes_file = <reserved_nodes_file>
owners_file = <owners_file>
repeater_channel_id = <channel_id>
messenger_channel_id = <channel_id>